### ISSUE TITLE
计算metrics时遇到的问题

### ISSUE THREAD

**Issue by yayinliqing** [ChrisDud0257/HGGT#8]
FileNotFoundError: [Errno 2] No such file or directory: '../../results/LDL_DF2K_OST_Blind_x4/visualization/psnr_ssim_Test-100.txt'

**Comment by ChrisDud0257** [comment]
这个不是代码的问题，请仔细阅读README的Step 6: Evaluation metrics的操作说明
1.首先确保下载了我们训练好的最终的SR图像的结果并且保存在一个文件夹中，或者用你自己训练好的SR图像的结果也行。保存结果的文件夹一定要有
2.参考Step 6: Evaluation metrics里面的说明，修改args.restored的路径，指向第一步中你保存好的SR结果的文件夹
上面两步操作任何一步出现问题都会导致no such file的报错

**Comment by yayinliqing** [comment]
> 这个不是代码的问题，请仔细阅读README的Step 6: Evaluation metrics的操作说明 1.首先确保下载了我们训练好的最终的SR图像的结果并且保存在一个文件夹中，或者用你自己训练好的SR图像的结果也行。保存结果的文件夹一定要有 2.参考Step 6: Evaluation metrics里面的说明，修改args.restored的路径，指向第一步中你保存好的SR结果的文件夹 上面两步操作任何一步出现问题都会导致no such file的报错

保存结果的文件夹已经有了，并且也修改args.restored的路径，错误是没有psnr_ssim_Test-100.txt这个文件

**Comment by yayinliqing** [comment]
作者你好，保存结果的文件夹已经有了（但是文件夹里面没有psnr_ssim_Test-100.tx），并且也修改args.restored的路径，错误是因为没有psnr_ssim_Test-100.txt这个文件




2947273697
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChrisDud0257/HGGT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月25日(星期三) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChrisDud0257/HGGT] 计算metrics时遇到的问题 (Issue #8)





 
这个不是代码的问题，请仔细阅读README的Step 6: Evaluation metrics的操作说明
 1.首先确保下载了我们训练好的最终的SR图像的结果并且保存在一个文件夹中，或者用你自己训练好的SR图像的结果也行。保存结果的文件夹一定要有
 2.参考Step 6: Evaluation metrics里面的说明，修改args.restored的路径，指向第一步中你保存好的SR结果的文件夹
 上面两步操作任何一步出现问题都会导致no such file的报错

**Comment by yayinliqing** [comment]
> > 这个不是代码的问题，请仔细阅读README的Step 6: Evaluation metrics的操作说明 1.首先确保下载了我们训练好的最终的SR图像的结果并且保存在一个文件夹中，或者用你自己训练好的SR图像的结果也行。保存结果的文件夹一定要有 2.参考Step 6: Evaluation metrics里面的说明，修改args.restored的路径，指向第一步中你保存好的SR结果的文件夹 上面两步操作任何一步出现问题都会导致no such file的报错
> 
> 保存结果的文件夹已经有了，并且也修改args.restored的路径，错误是没有psnr_ssim_Test-100.txt这个文件

代码直接连已经存在的文件夹都找不到了

**Comment by ChrisDud0257** [comment]
psnr_ssim_Test-100.txt这个文件在测试开始之前肯定不会有啊，原理首先弄明白。这个txt是在测试过程中生成的，测试过程会生成一个txt文件，然后把指标记录下来存入到这个txt里面，在测试之前怎么可能会存在这个文件呢？

**Comment by yayinliqing** [comment]
> psnr_ssim_Test-100.txt这个文件在测试开始之前肯定不会有啊，原理首先弄明白。这个txt是在测试过程中生成的，测试过程会生成一个txt文件，然后把指标记录下来存入到这个txt里面，在测试之前怎么可能会存在这个文件呢？

/

**Comment by yayinliqing** [comment]
> psnr_ssim_Test-100.txt这个文件在测试开始之前肯定不会有啊，原理首先弄明白。这个txt是在测试过程中生成的，测试过程会生成一个txt文件，然后把指标记录下来存入到这个txt里面，在测试之前怎么可能会存在这个文件呢？

问题是我每次刚开始执行python ./scripts/metrics/calculate_multigt_labeled_psnr_ssim.py --restored ../../results/BSRGAN_DF2K_OST_Blind_Ori_x4/visulization/Test-100就会直接报错
    save_txt = open(save_txt_path, mode='w', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: '../../results/BSRGAN_DF2K_OST_Blind_Ori_x4/visulization/psnr_ssim_Test-100.txt'

**Comment by yayinliqing** [comment]
> > psnr_ssim_Test-100.txt这个文件在测试开始之前肯定不会有啊，原理首先弄明白。这个txt是在测试过程中生成的，测试过程会生成一个txt文件，然后把指标记录下来存入到这个txt里面，在测试之前怎么可能会存在这个文件呢？
> 
> 问题是我每次刚开始执行python ./scripts/metrics/calculate_multigt_labeled_psnr_ssim.py --restored ../../results/BSRGAN_DF2K_OST_Blind_Ori_x4/visulization/Test-100就会直接报错 save_txt = open(save_txt_path, mode='w', encoding='utf-8') FileNotFoundError: [Errno 2] No such file or directory: '../../results/BSRGAN_DF2K_OST_Blind_Ori_x4/visulization/psnr_ssim_Test-100.txt'

就算我自己创建该文本文件，仍然会有相同的错误

**Comment by ChrisDud0257** [comment]
我刚才重新跑了一下这个测试代码，我自己的路径下能正确运行，而且可以生成测试结果的文件，
![image](https://github.com/ChrisDud0257/HGGT/assets/128046921/2307e89a-f618-473c-a1a8-29b73eeb06e0)

所以我并不是很清楚你是怎么弄的，你为什么要自己创建这个txt文本文件，我已经解释的很清楚了，psnr_ssim_Test-100.txt这个文件是代码生成的，不需要你自己去手动创建一个？再者，我看你的报错，你确定你有“../../results/BSRGAN_DF2K_OST_Blind_Ori_x4/visulization/‘’这个文件夹吗？这个很明显我感觉你并没有这个文件夹。以及，“../../”这个相对路径用对了吗？如果还是不行，你自己随便把'../../results/BSRGAN_DF2K_OST_Blind_Ori_x4/visulization/psnr_ssim_Test-100.txt'这个路径改为“/your path/psnr_ssim_Test-100.txt”,your path是你本地的任何一个已经存在的文件夹，如果还是出错，建议先去请教百度，python创建并且写入txt相关的教程。

**Comment by yayinliqing** [comment]
> 我刚才重新跑了一下这个测试代码，我自己的路径下能正确运行，而且可以生成测试结果的文件， ![image](https://user-images.githubusercontent.com/128046921/278567340-2307e89a-f618-473c-a1a8-29b73eeb06e0.png)
> 
> 所以我并不是很清楚你是怎么弄的，你为什么要自己创建这个txt文本文件，我已经解释的很清楚了，psnr_ssim_Test-100.txt这个文件是代码生成的，不需要你自己去手动创建一个？再者，我看你的报错，你确定你有“../../results/BSRGAN_DF2K_OST_Blind_Ori_x4/visulization/‘’这个文件夹吗？这个很明显我感觉你并没有这个文件夹。以及，“../../”这个相对路径用对了吗？如果还是不行，你自己随便把'../../results/BSRGAN_DF2K_OST_Blind_Ori_x4/visulization/psnr_ssim_Test-100.txt'这个路径改为“/your path/psnr_ssim_Test-100.txt”,your path是你本地的任何一个已经存在的文件夹，如果还是出错，建议先去请教百度，python创建并且写入txt相关的教程。

已经解决了，就是把../../改成了./，感谢感谢
